// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-processings.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-processings.ts
var list_processings_default = defineTool({
  name: "list_processings",
  title: "List processing runs",
  description: "List the signed-in user's file processing runs with their extraction statistics.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of runs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("processamentos").select("id, created_at, status_geral, arquivos_recebidos, arquivos_sucesso, arquivos_com_falha, shows_extraidos, setlists_criados, musicas_catalogadas").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { processings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-shows.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_shows_default = defineTool2({
  name: "list_shows",
  title: "List shows",
  description: "List catalogued live shows for the signed-in user, optionally filtered by artist, city or processing run.",
  inputSchema: {
    artist: z2.string().trim().optional().describe("Filter by artist name (partial match)."),
    city: z2.string().trim().optional().describe("Filter by city name (partial match)."),
    processingId: z2.string().trim().optional().describe("Restrict to one processing run id."),
    limit: z2.number().int().min(1).max(200).default(50).describe("Maximum number of shows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ artist, city, processingId, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("shows").select("id, processamento_id, artist, date, territory, city, venue, venue_address, set_list_number, headliner_yn, headliner_name, status").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (artist) query = query.ilike("artist", `%${artist}%`);
    if (city) query = query.ilike("city", `%${city}%`);
    if (processingId) query = query.eq("processamento_id", processingId);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { shows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-setlist-songs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_setlist_songs_default = defineTool3({
  name: "list_setlist_songs",
  title: "List setlist songs",
  description: "List songs from the signed-in user's setlists, optionally filtered by processing run, setlist number or title.",
  inputSchema: {
    processingId: z3.string().trim().optional().describe("Restrict to one processing run id."),
    setListNumber: z3.number().int().optional().describe("Restrict to one setlist number."),
    title: z3.string().trim().optional().describe("Filter by song title (partial match)."),
    limit: z3.number().int().min(1).max(300).default(100).describe("Maximum number of songs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ processingId, setListNumber, title, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("setlists").select("id, processamento_id, set_list_number, ordem, song_title, composers, bmg_control, imaestro_code, prs_tunecode, comments").order("set_list_number", { ascending: true }).order("ordem", { ascending: true }).limit(limit ?? 100);
    if (processingId) query = query.eq("processamento_id", processingId);
    if (typeof setListNumber === "number") query = query.eq("set_list_number", setListNumber);
    if (title) query = query.ilike("song_title", `%${title}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { songs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-processing-errors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_processing_errors_default = defineTool4({
  name: "list_processing_errors",
  title: "List processing errors",
  description: "List parsing/processing errors recorded for the signed-in user's uploads.",
  inputSchema: {
    processingId: z4.string().trim().optional().describe("Restrict to one processing run id."),
    onlyUnresolved: z4.boolean().default(false).describe("Return only errors that are not marked resolved."),
    limit: z4.number().int().min(1).max(200).default(50).describe("Maximum number of errors to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ processingId, onlyUnresolved, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("erros_processamento").select("id, processamento_id, arquivo_nome, tipo_erro, descricao, linha_afetada, metodo_tentado, resolvido, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (processingId) query = query.eq("processamento_id", processingId);
    if (onlyUnresolved) query = query.eq("resolvido", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { errors: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fvpxvbklwtxtlzmlytkd";
var mcp_default = defineMcp({
  name: "setlist-symphony",
  title: "Setlist Symphony",
  version: "0.1.0",
  instructions: "Tools for Setlist Symphony, a live-performance catalog. Use `list_processings` to find processing runs, `list_shows` for catalogued shows, `list_setlist_songs` for songs and composers, and `list_processing_errors` to inspect parsing problems. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_processings_default, list_shows_default, list_setlist_songs_default, list_processing_errors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
